services:
  vote:
    image: isrealurephu/vote:latest
    depends_on:
     redis:
       condition: service_healthy
    ports:
      - "8090:80"
   
  result:
    image: isrealurephu/result:latest
    volumes:
      - ./result:/usr/local/app
    ports:
      - "8091:80"

  worker:
    image: isrealurephu/worker:latest
     

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes
      - db_data:/var/lib/postgresql/data
  
volumes:
  redis_data:
  db_data:
