name: deploy to ec2
on:
    push:
        branches:
            - main
        paths:
            - result/**
            - vote/**
            - worker/**
            - .github/workflows/build.yaml
            - docker-compose.yaml
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code 
              uses: actions/checkout@
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: login to dockerhub 
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push vote service
              uses: docker/build-push-action@v4
              with:
                context: ./vote
                file: ./vote/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/vote:latest
                target: dev

            - name: Build and push result service
              uses: docker/build-push-action@v4
              with:
                context: ./result
                file: ./result/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/result:latest

            - name: Build and push worker service
              uses: docker/build-push-action@v4
              with:
                context: ./worker
                file: ./worker/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/worker:latest
              